name: Harvest Notification

on:
  schedule:
    - cron: '0 8 * * *' #runs every day at 8:00 UTC
  workflow_dispatch: #allows manual trigger

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_LOGIN: ${{ secrets.SMTP_LOGIN }}
      SMTP_LOGIN_PASSWORD: ${{ secrets.SMTP_LOGIN_PASSWORD }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      db_user: ${{ secrets.db_user }}
      db_password: ${{ secrets.db_password }}
      db_host: ${{ secrets.db_host }}
      db_port: ${{ secrets.db_port }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary python-dotenv
      - name: Run harvest notification script
        run: python harvestdate_check.py
